jenkinsci/aws-credentials-plugin

- pom.xml
Remove optional on credentials-binding dependency, as is causing other plugins with transitive dependency to it to fail.
@reviewbybees
> Remove optional on credentials-binding dependency

- .gitignore
- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
- src/main/resources/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl/credentials.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl/help-iamMfaSerialNumber.html
- src/main/resources/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl/help-iamMfaToken.html
- src/main/resources/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl/help-iamRoleArn.html
- src/main/resources/com/cloudbees/jenkins/plugins/awscredentials/Messages.properties
> Add support for assuming IAM roles

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
See [JENKINS-41967](https://issues.jenkins-ci.org/browse/JENKINS-41967)
@reviewbybees
> [JENKINS-41967] Restore old constructor to maintain binary compatibility

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AmazonWebServicesCredentialsBinding.java
Two changes in this PR.
To use e.g AWS CLI with AssumeRole support, an `AWS_SESSION_TOKEN` variable must be set, or AWS would complain that no access key is found on record. This variable is only bound if credentials returned by the credentials provider are session-based.
Fixes #19  
To further support moving away from hard-set AWS Credentials and allow role switching (e.g cross-account access), this PR also adds following behavior:
If no access & secret keys are set as part of credentials, but IAM role *is* set -  attempting to fetch credentials via instance profile.
Fixes #18 #15 
Motivation for both changes is to simplify management of multi-AWS account environments and to remove useage of Access/Secret keys which should be rotated quite often according to security best-practices. …
> Assume Role support improvements

- pom.xml
Otherwise it does not build if you have no cached Parent POM XML
@reviewbybees
> Add repositories and plugin repositories to POM.xml

- pom.xml
When a plugin was depending on older version of credentials plugin it causes findbugs-annotations.jar to be included in packaging.  This should bring things more closer to actual user  environments (upgraded to credentials 2.x)
@reviewbybees
> Updating to use latest verified version of credentials plugin

- pom.xml
In order to bump credentials to 2.x (https://github.com/jenkinsci/aws-credentials-plugin/pull/31)  we need to bump to jdk7 and update jenkins baseline accordingly.  Should be relatively safe since this is still an older version of jenkins
@reviewbybees
> bumped to jdk7, bumped jenkins baseline to match jdk7 requirement

- .mvn/extensions.xml
- .mvn/maven.config
- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
- src/main/resources/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl/help-accessKey.html
- src/main/resources/index.jelly
`InstanceProfileCredentialsProvider` only works under limited conditions. It is simpler and better to use the default provider chain from the AWS SDK.
May fix #29. Amends #20. Subsumes #41.
Who is the maintainer these days? CC @carlossg
> Correcting default credentials when using assumed roles

- pom.xml
Was incorrect, perhaps from a prior rename of the plugin.
> Fixing scm/connection

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSDeclarativeCredentialsHandler.java
See [JENKINS-53101](https://issues.jenkins-ci.org/browse/JENKINS-53101)
Supersedes https://github.com/jenkinsci/aws-credentials-plugin/pull/45 and https://github.com/jenkinsci/aws-credentials-plugin/pull/49
> [JENKINS-53101] Add Declarative credentials handler for AWS creds

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
Fixes https://github.com/jenkinsci/aws-credentials-plugin/issues/47
> Define default region for STS actions to fix regression introduced in 1.24

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AmazonWebServicesCredentialsBinding.java
- src/main/resources/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl/credentials.jelly
- src/main/resources/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl/help-stsTokenDuration.html
- src/main/resources/com/cloudbees/jenkins/plugins/awscredentials/Messages.properties
Based off of https://github.com/jenkinsci/aws-credentials-plugin/pull/43, but attempts to address the changes requested by @andresrc at https://github.com/jenkinsci/aws-credentials-plugin/pull/43#pullrequestreview-198318491
> Configurable Session Token Duration

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSDeclarativeCredentialsHandler.java
Can @abayer @amuniz please review it?
pipeline-model-extensions doesn't seem to be a required dependency. It is since https://github.com/jenkinsci/aws-credentials-plugin/pull/50 had been merged introducing undesired transitive dependencies.
> [FIXED JENKINS-57426] Make pipeline-model-extensions dependency optional

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
What could possibly go wrong when one uses a localized field for an AWS request session name? I have no idea why this field is used, maybe somebody overrides the "Jenkins" name in such way. I leave a full fix to the plugin maintainers who know the use-case, just fixing an obvious issue reported in https://issues.jenkins-ci.org/browse/JENKINS-58842
Fixes #67 
CC @diegombeltran
> [JENKINS-58842] - Trim Jenkins name for Role Session Names to avoid issues with trailing spaces in localizations

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AmazonWebServicesCredentialsBinding.java
Since the AWS credential type is managing two secret strings
(`accessKeyVariable` / `secretKeyVariable`), there is no need for a
workspace to access those secrets.
> JENKINS-57075 Remove workspace requirement

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AmazonWebServicesCredentialsBinding.java
According to [existing bindings](https://jenkins.io/doc/pipeline/steps/credentials-binding/#withcredentials-bind-credentials-to-variables) this seems a reasonable choice. E.g.
```groovy
withCredentials([aws(credentialsId: '…')]) {
sh 'aws …'
}
```
> Add a @Symbol to AmazonWebServicesCredentialsBinding

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
This is a follow-up of 
* https://github.com/jenkinsci/aws-credentials-plugin/issues/44
* https://issues.jenkins-ci.org/browse/JENKINS-60057
The idea is that AssumeRole gets the proxy configuration from Jenkins.
> [JENKINS-60057] AssumeRole does not honour proxy settings

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
* Auto-format `AWSCredentialsImpl.java`
* Change exception type from `AmazonServiceException` to `RuntimeException`
When garbage data is provided in the AWS credential configuration, the Amazon SDK throws a (previously uncaught) `SdkClientException` e.g. "unable to determine region ..." which caused an angry Jenkins to appear below the `secretKey` field. Now that the broad exception is caught, a much better looking error is shown which relays information about the `SdkClientException`.
Note: `AmazonServiceException` [is a subclass of](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/SdkClientException.html) `SdkClientException` and `RuntimeException`.
> Fix angry jenkins with broader exception handling

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AmazonWebServicesCredentialsBinding.java
Fixes #80.
We have been using this feature on our CloudBees instance for several months now. We have not experienced any issues with it. We have been fetching credentials in two ways:
1. `credentialsId`, `roleArn` and `roleSessionName` provided
2. `credentialsId`, `accessKeyVariable`, and `secretKeyVariable` provided
Both have been working flawlessly.
In addition, when implementing this change, I did integration testing on our CloudBees instance to cover the following cases:
1. `credentialsId`, `roleArn`, `roleSessionName`, and `roleSessionDurationSeconds`
2. `credentialsId` and `roleArn`
3. `credentialsId` and `roleArn`, with `roleSessionName` as the empty string
4. `credentialsId`, with `roleArn` as the empty string
5. just `credentialsId`
All of these cases passed, as verified by …
> Allow specifying AWS role at runtime

- pom.xml
Since 1.12.70, the `aws-java-sdk` plugin has been split into multiple fine-grained plugins.
This pull request replaces the heavyweight `aws-java-sdk` (195Mb) with a fine-grained `aws-java-sdk-ec2` dependency.
> Replace heavyweight aws-java-sdk with fine-grained aws-java-sdk-ec2

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSDeclarativeCredentialsHandler.java
See https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/418: unused as of `pipeline-model-definition` 1.1.4 (older than the dep here).
> Deleting `CredentialsBindingHandler.toBindings`

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
- src/main/resources/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl/credentials.jelly
- src/test/java/com/cloudbees/jenkins/plugins/awscredentials/ConfigurationAsCodeTest.java
- src/test/resources/com/cloudbees/jenkins/plugins/awscredentials/configuration-as-code.yaml
Support for externalID when using role
When assuming role an external ID value may also need to be specified.
This change implements the use of external ID.
> [JENKINS-65105]: Support for externalID when using role

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
Fixes #116 
check the `externalId` is not blank or empty before adding it.
this covers the existing case where a credential was created before the externalId field was introduced (null) as well as after it was where it would be converted to an empty String (which is not a valid external id)
> [JENKINS-67452] Do not add blank external ids

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AmazonWebServicesCredentialsBinding.java
> Silence warnings for fields with no getters

- pom.xml
- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AmazonWebServicesCredentials.java
- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AmazonWebServicesCredentialsBinding.java
Tested in context by calling the `doCheckSecretKey` validation endpoint and verifying that validation succeeded using the AWS SDK for Java 2.x and that the call to EC2 succeeded. Took away EC2 read permissions and confirmed the correct error message was displayed. Created a Squid proxy and verified that validation still succeeded through the proxy. Took down the proxy and verified that validation failed when the proxy was configured but not responding. Tested the compatibility layer by running a Pipeline job with unmodified `aws-global-credentials` and `artifact-manager-s3` plugins, and verified that the artifact showed up in S3.
> [JENKINS-73649] Use AWS SDK for Java 2.x

- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AWSCredentialsImpl.java
- src/main/java/com/cloudbees/jenkins/plugins/awscredentials/AmazonWebServicesCredentialsBinding.java
Only use the accessKey and secretKey if they are provided. Before it was only checking if role was blank. This allows the creation of a secret that uses the instance profile. This is useful if you want to parameterize the secret being passed in - one for the instance profile and a different one for a different account. This functionality existed before in earlier versions of the plugin, this is restoring that functionality.
Fixes https://github.com/jenkinsci/aws-credentials-plugin/issues/264
* Installed latest version `240.v6d844a_6f5480`
* Created two credentials:
* one named `withKey` that had a valid access and secret access key (from a second account) and blank role
* one named `withBlanks` that had a blank access key, blank secret access key, and blank role
* Ran a job that called …
> Only use `accessKey` and `secretKey` if they are not blank
